spring:
  application:
    name: first-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gcs3
    username: gcs
    password: gcs
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 50
      data-source-properties:
        currentSchema: test1
      auto-commit: false
  flyway:
    enabled: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-core.xml
  sql:
    init:
      mode: always
  elasticsearch:
    uris: [ "http://localhost:9200" ]

management:
  endpoints:
    web:
      base-path: /sys
      exposure:
        include: health,info,metrics,heapdump,threaddump,configprops,env,shutdown
  tracing:
    enabled: true
    sampling:
      probability: 1.0

javamelody:
  enabled: true
  spring-monitoring-enabled: false
  resolution-seconds: 30

opentracing:
  jaeger:
    log-spans: false